name: Automated API Tests
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
  
      - name: Install Apidog CLI
        run: npm install -g apidog-cli
  
      - name: Running Test Scenario
        run: |
          apidog run https://api.apidog.com/api/v1/projects/469204/api-test/ci-config/349543/detail?token=xdGMPHHcIsP80b1GLkpfHV -r json
          mv apidog_report.json $GITHUB_WORKSPACE/apidog_report.json

      - name: Archive JSON report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: apidog_report
          path: apidog_report.json
