name: Automated API Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Apidog CLI
      run: npm install -g apidog-cli

    - name: Running Test Scenario
      run: apidog run https://api.apidog.com/api/v1/projects/469204/api-test/ci-config/349543/detail?token=xdGMPHHcIsP80b1GLkpfHV -r html,cli
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: ${{ github.workspace }}/apidog-reports/**/*
    - name: Send email with HTML report
      run: node sendEmail.js
      env:
                SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
