name: Run APIdog Tests and Send Email
on:
  workflow_dispatch

jobs:
  test_and_send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SendGrid library
        run: npm install @sendgrid/mail
        
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install APIdog CLI
        run: npm install -g apidog-cli

      - name: Run APIdog tests and generate HTML report
        run: |
          # Download the APIdog report
          curl -o .github/Reports/apidog_report.html "https://api.apidog.com/api/v1/projects/469204/api-test/ci-config/349543/detail?token=xdGMPHHcIsP80b1GLkpfHV"
          
          # Generate the report using APIdog (replace with your actual command)
          apidog run https://api.apidog.com/api/v1/projects/469204/api-test/ci-config/349543/detail?token=xdGMPHHcIsP80b1GLkpfHV -r cli

          # Move the generated report to the correct location
          mv apidog_report.html .github/Reports/

      - name: Send email with HTML report
        run: node sendEmail.js
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
