name: Run APIdog Tests and Send Email
on: workflow_dispatch
  # push:
  #   branches:
  #     - main  # Trigger the workflow on pushes to the main branch
jobs:
  test_and_send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install SendGrid library
        run: npm install @sendgrid/mail
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install APIdog CLI
        run: npm install -g apidog-cli
      - name: Run APIdog tests and generate HTML report
        run: |
          apidog run https://api.apidog.com/api/v1/projects/469204/api-test/ci-config/349543/detail?token=xdGMPHHcIsP80b1GLkpfHV -r json > apidog-report.json
          cat apidog-report.json  # Display the content of the JSON file for debugging
        continue-on-error: true  # Continue with the next step even if there's an error

      - name: Check Apidog report
        run: |
          cat apidog-report.json
          if [ ! -s "apidog-report.json" ]; then
          echo "Apidog report is empty or does not exist"
          exit 1
          fi

      - name: Generate Newman report
        run: newman run apidog-report.json -r html

      - name: Upload Newman HTML report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: newman
      - name: Send email with HTML report
        run: node sendEmail.js
        env:
                SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
