name: Automated API Tests
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
  
      - name: Install Apidog CLI
        run: npm install -g apidog-cli
  
      - name: Running Test Scenario
        run: |
          apidog run https://api.apidog.com/api/v1/projects/469204/api-test/ci-config/349543/detail?token=xdGMPHHcIsP80b1GLkpfHV -r json
          ls -la  # List files in the current directory for debugging
          mv apidog_output.json apidog_report.json || true  # Rename the output to match the expected name, ignoring errors if the file doesn't exist
          mkdir -p .github/Reports  # Create the Reports folder if it doesn't exist
          if [ -f apidog_report.json ]; then  # Check if the file exists before moving it
            mv apidog_report.json .github/Reports/apidog_report.json  # Move the report to the Reports folder
          else
            echo "ERROR: apidog_report.json not found!"
            exit 1
          fi

      - name: Archive JSON report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: apidog_report
          path: .github/Reports/apidog_report.json
