name: Automated API Tests
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
  
      - name: Install Apidog CLI
        run: npm install -g apidog-cli
  
      - name: Running Test Scenario
        run: |
          apidog run https://api.apidog.com/api/v1/projects/469204/api-test/ci-config/349543/detail?token=xdGMPHHcIsP80b1GLkpfHV -r json
          report_file=$(find . -maxdepth 1 -name '*.json' -print -quit)  # Find the JSON report file
          if [ -n "$report_file" ]; then  # Check if a JSON report file was found
            mv "$report_file" apidog_report.json  # Rename the JSON report file to apidog_report.json
            mkdir -p .github/Reports  # Create the Reports folder if it doesn't exist
            mv apidog_report.json .github/Reports/apidog_report.json  # Move the report to the Reports folder
          else
            echo "ERROR: JSON report file not found!"
            exit 1
          fi

      - name: Archive JSON report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: apidog_report
          path: .github/Reports/apidog_report.json
