name: Run APIdog Tests and Send Email
on: workflow_dispatch
  # push:
  #   branches:
  #     - main  # Trigger the workflow on pushes to the main branch
jobs:
  test_and_send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install SendGrid library
        run: npm install @sendgrid/mail
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install APIdog CLI
        run: npm install -g apidog-cli
      - name: Create apidog-reports directory
        run: mkdir -p apidog-reports

      - name: Run APIdog tests and generate JSON report
        run: |
          apidog run https://api.apidog.com/api/v1/projects/469204/api-test/ci-config/349543/detail?token=xdGMPHHcIsP80b1GLkpfHV -r json | tee apidog-report.json

      - name: Upload Apidog JSON report
        uses: actions/upload-artifact@v3
        with:
          name: apidog-report
          path: ${{ github.workspace }}/apidog-report.json
      - name: Send email with HTML report
        run: node sendEmail.js
        env:
                SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
