name: Run APIdog Tests and Send Email
on:
  workflow_dispatch

jobs:
  test_and_send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SendGrid library
        run: npm install @sendgrid/mail
        
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install APIdog CLI
        run: npm install -g apidog-cli
        
      - name: Create testArtifacts directory (if needed)
        run: mkdir -p testArtifacts

      - name: Run APIdog tests and generate HTML report
        env:
          APIDOG_TOKEN: ${{ secrets.APIDOG_TOKEN }}  # Access token from secret
        run: |
          apidog run \
            https://api.apidog.com/api/v1/projects/469204/api-test/ci-config/349543/detail?token=$APIDOG_TOKEN \
            -r html
      - name: Verify and move HTML report (if found)
        run: |
          if [ -f "apidog_report.html" ]; then
            echo "HTML report found"
            mv apidog_report.html .github/Reports/
          fi

      - name: Move HTML report (if it exists)
        run: |
          if [ -f "apidog_report.html" ]; then
            mv apidog_report.html .github/Reports/
          fi
      
      - name: Output the results (downloaded report)
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: testArtifacts

      - name: Send email with HTML report
        run: node sendEmail.js
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
